version: '3'

services:
  postgres:
    container_name: db
    image: postgres:14.5
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/.data/postgres:/var/lib/postgresql/data
      - ./script/load-extensions.sh:/docker-entrypoint-initdb.d/load-extensions.sh
    restart: unless-stopped
    environment:
      POSTGRES_USER: "nestjs"
      POSTGRES_PASSWORD: "nestjs"
      POSTGRES_DB: "boilerplate-db"
    networks:
      - nestjs_redis_queue_net
  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    ports:
      - "16379:6379"
    networks:
      - nestjs_redis_queue_net
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: nestjs@boilerplate.com
      PGADMIN_DEFAULT_PASSWORD: nestjs
    volumes:
      - ${HOME}/.data/pgadmin:/root/.pgadmin
    networks:
      - nestjs_redis_queue_net
    links:
      - postgres
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
networks:
  nestjs_redis_queue_net:
    driver: bridge
volumes:
  postgres:
    driver: local
